In [1]:
import os, cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
PATH = os.getcwd()
# Define data path
data_path = PATH + '/test'
data_dir_list = os.listdir(data_path)

In [15]:
#inisialisasi
img_row = 28
img_col = 28
num_channel = 1
img_data_list= []

##Mencari dan mengubah masing-masing gambar dalam tiap2 folder, 
##lalu mengubah sesuai format dan ukuran standard yang ditentukan 
for dataset in data_dir_list:
    img_list=os.listdir(data_path+'/'+ dataset) #Mencari dan mendeteksi tiap-tiap folder
    print ('Loaded the images of dataset-'+'{}\n'.format(dataset))
    for img in img_list:
        input_img=cv2.imread(data_path + '/'+ dataset + '/'+ img ) #membaca masing-masing data gambar dan mengubah ke dalam biner
        input_img=cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY) #mengubah tiap-tiap gambar menjadi format warna grayscale
        input_img_resize=cv2.resize(input_img,(img_row,img_col)) #resize ukuran gambar sesuai dengan img_row dan img_col
        input_img_resize = input_img_resize.reshape(img_row*img_col) #mengubah ukuran matriks menjadi satu baris contoh: dari 50x50 menjadi 1x2500
        img_data_list.append(input_img_resize) #menambahkan baris diatas ke dalam data list(img_data_list)

img_data = np.array(img_data_list) #mengubah img_data_list yang berbentuk list menjadi bentuk array
img_data = img_data.astype('float32') #mengubah setiap elemen data img_data menjadi float32
print (img_data.shape)

Loaded the images of dataset-PNEUMONIA

Loaded the images of dataset-NORMAL

(624, 784)


In [16]:
#img data dalam bentuk dataframe
df0 = pd.DataFrame(img_data)
df0


0      1      2      3      4      5      6      7      8      9    \
0     33.0   40.0   57.0   62.0   55.0   73.0   49.0   49.0   45.0   70.0   
1     39.0   16.0  150.0  123.0   67.0   53.0   58.0  148.0  174.0  170.0   
2    208.0  144.0  198.0   60.0   76.0   82.0  119.0  111.0  119.0  127.0   
3    104.0   74.0   79.0   74.0   82.0   73.0   70.0   91.0   80.0   90.0   
4     46.0   93.0  117.0  136.0  162.0  172.0  169.0  184.0  225.0  200.0   
5      0.0  250.0   10.0   65.0   94.0   85.0   95.0  131.0  150.0  196.0   
6    138.0  149.0  152.0  129.0   95.0   92.0  101.0  151.0   91.0  126.0   
7      0.0    7.0   89.0  116.0  154.0  160.0  129.0  160.0  132.0  130.0   
8     50.0   54.0   69.0   71.0   83.0   74.0   97.0  103.0  115.0  124.0   
9     42.0   60.0   70.0   86.0   78.0   79.0   75.0  100.0   90.0  108.0   
10   159.0  163.0   79.0   93.0  123.0  125.0  120.0  175.0  187.0  176.0   
11    63.0   65.0   64.0   69.0   56.0   78.0  102.0  128.0  152.0  118.0   
12   114.0  127.0  148.0  141.0  147.0  126.0  139.0  132.0  144.0  190.0   
13    32.0  108.0   54.0   68.0   88.0  135.0  151.0  187.0  129.0  140.0   
14     0.0    1.0   19.0   88.0  124.0  140.0  154.0  163.0  183.0  205.0   
15    89.0   64.0   57.0   50.0   74.0   71.0   44.0   54.0   62.0   88.0   
16   209.0  197.0  187.0   91.0    5.0    9.0   10.0    6.0   41.0   58.0   
17    17.0   42.0  134.0  187.0   31.0   37.0   44.0   43.0   74.0  110.0   
18    17.0   11.0    5.0   64.0   84.0   76.0   58.0   33.0   31.0   43.0   
19     9.0   35.0   47.0   56.0  153.0  183.0  177.0  168.0  186.0  196.0   
20    97.0  153.0  131.0  128.0  134.0  152.0  149.0  151.0  176.0  184.0   
21    55.0   41.0   85.0   69.0   78.0   58.0   95.0   66.0   68.0  106.0   
22    13.0   81.0  127.0  148.0  161.0  155.0  149.0  179.0  175.0  135.0   
23   183.0   90.0   30.0    7.0    6.0    4.0   23.0   52.0   78.0  102.0   
24    80.0   76.0   57.0   59.0   72.0   59.0   58.0   87.0   73.0  106.0   
25    50.0   32.0   34.0   66.0   94.0   89.0   92.0  104.0  149.0  165.0   
26    41.0   46.0   46.0   47.0   74.0   88.0  152.0  149.0  172.0  178.0   
27    34.0   79.0   81.0   49.0   45.0   33.0   67.0  115.0   91.0  135.0   
28   195.0  102.0   62.0   62.0   67.0   74.0   74.0  108.0  141.0  154.0   
29    12.0   61.0   68.0   64.0   61.0   59.0   72.0   61.0   56.0  124.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
594   26.0   61.0  101.0  141.0  106.0  135.0  124.0  135.0  161.0  166.0   
595   82.0  122.0  128.0  147.0  119.0  104.0   64.0   10.0   36.0   88.0   
596   37.0   61.0   63.0   74.0   88.0   70.0   83.0  120.0   95.0   86.0   
597   54.0  104.0  127.0  134.0  141.0  119.0  101.0  101.0  126.0  170.0   
598   27.0   24.0  254.0   14.0   31.0   53.0   69.0   92.0  108.0  130.0   
599   11.0   90.0  134.0  173.0  169.0  154.0  162.0  164.0  163.0  159.0   
600    0.0   99.0  120.0  122.0  134.0   95.0  108.0  115.0  133.0  159.0   
601   18.0   95.0  139.0  170.0  169.0  187.0  168.0  199.0  187.0  201.0   
602   20.0   47.0   63.0   58.0   47.0  114.0  134.0  173.0  162.0  164.0   
603    0.0   23.0   53.0   85.0   82.0  103.0   84.0   74.0   23.0  110.0   
604    0.0   35.0   69.0   93.0  102.0  140.0  133.0  136.0  134.0  111.0   
605   18.0   73.0  125.0  123.0  172.0  160.0  149.0  175.0  158.0  181.0   
606   32.0   27.0   28.0   30.0   23.0  254.0   23.0   49.0   85.0  123.0   
607  111.0  124.0  106.0   95.0   75.0   72.0   64.0  100.0  119.0  119.0   
608    0.0   22.0   68.0   81.0  141.0  207.0  193.0  194.0  232.0  238.0   
609  142.0  143.0  157.0  111.0   93.0   85.0   49.0    0.0   18.0   61.0   
610   25.0   25.0   23.0   22.0   18.0   22.0   58.0  100.0  117.0  129.0   
611    0.0   78.0   58.0  111.0  122.0  109.0  106.0   79.0   93.0  144.0   
612   38.0   87.0  103.0  148.0  113.0  109.0   92.0   68.0  155.0  162.0   
613   13.0   13.0    7.0   45.0   74.0   92.0  103.0   95.0  120.0  150.0   
614

In [17]:
labels=[]
#Menentukan label pada data sesuai dengan jumlah data pada masing-masing folder
#satu folder merepresentasikan label tertentu
lbl1 = np.ones(390)
lbl2 = np.zeros(234)
labels.append(lbl1)
labels = np.array(labels)
labels.resize()
for i in range(len(lbl2)):
    labels = np.append(labels, lbl2[i])
#labels = labels.reshape(20)

labels = labels.reshape(624,1)

print(labels.shape)
labels

(624, 1)


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [18]:
#menambahkan label yang sudah dibuat ke dalam data
img_data_label = np.insert(img_data, [0], labels, axis=1)
img_data_label

array([[  1.,  33.,  40., ...,  16.,  22.,  24.],
       [  1.,  39.,  16., ...,  31.,  16.,  19.],
       [  1., 208., 144., ...,  73.,  25.,  14.],
       ...,
       [  0.,  13.,  13., ...,   9.,   9.,   9.],
       [  0., 107., 126., ...,   0.,   6.,   4.],
       [  0., 160., 137., ..., 161.,  29., 251.]], dtype=float32)

In [8]:
#shuffling baris (axis x)
np.random.shuffle(img_data_label)
img_data_label

array([[  0.,  15.,  14., ...,   8.,  11.,  12.],
       [  1., 121., 140., ...,  98.,  73.,  15.],
       [  1.,  23., 200., ...,  33.,  28.,  30.],
       ...,
       [  1.,  48., 136., ...,  15., 252.,   0.],
       [  1.,  10.,   1., ..., 178., 182.,  19.],
       [  1.,  86.,  95., ..., 176.,  78.,   1.]], dtype=float32)

In [9]:
# menampilkan dalam bentuk dataframe data yang sudah diberi label
df = pd.DataFrame(img_data_label)
df.head()

0      1      2      3      4      5      6      7      8      9    ...   \
0  0.0   15.0   14.0   10.0   30.0   62.0   88.0  109.0  129.0  114.0  ...    
1  1.0  121.0  140.0  151.0  170.0  171.0  194.0  196.0  188.0  172.0  ...    
2  1.0   23.0  200.0   21.0   22.0   25.0   26.0   25.0   22.0    6.0  ...    
3  1.0  101.0   82.0   90.0  100.0  137.0  145.0  178.0  125.0  141.0  ...    
4  0.0   70.0   90.0  167.0  179.0   95.0   82.0   33.0    0.0    0.0  ...    

     775    776    777    778    779    780    781    782    783   784  
0  176.0  179.0  164.0  177.0  184.0  141.0   50.0    8.0   11.0  12.0  
1  175.0  175.0  172.0  171.0  157.0  144.0  130.0   98.0   73.0  15.0  
2  126.0  114.0  100.0   99.0  101.0   69.0  110.0   33.0   28.0  30.0  
3  159.0  128.0  127.0  110.0  119.0  135.0  143.0  159.0  120.0  85.0  
4  214.0  211.0  198.0  210.0  203.0  191.0  166.0   56.0    0.0   0.0  

[5 rows x 785 columns]

In [10]:
#menambahkan header pada tiap-tiap kolom
col_header = ['label']
for i in range (784):
    pixel = 'pixel ' +str(i)
    col_header.insert((i+1),pixel)
col_header
#img_data_label.shape
df = pd.DataFrame(img_data_label, columns=col_header)
df.head()

label  pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  \
0    0.0     15.0     14.0     10.0     30.0     62.0     88.0    109.0   
1    1.0    121.0    140.0    151.0    170.0    171.0    194.0    196.0   
2    1.0     23.0    200.0     21.0     22.0     25.0     26.0     25.0   
3    1.0    101.0     82.0     90.0    100.0    137.0    145.0    178.0   
4    0.0     70.0     90.0    167.0    179.0     95.0     82.0     33.0   

   pixel 7  pixel 8    ...      pixel 774  pixel 775  pixel 776  pixel 777  \
0    129.0    114.0    ...          176.0      179.0      164.0      177.0   
1    188.0    172.0    ...          175.0      175.0      172.0      171.0   
2     22.0      6.0    ...          126.0      114.0      100.0       99.0   
3    125.0    141.0    ...          159.0      128.0      127.0      110.0   
4      0.0      0.0    ...          214.0      211.0      198.0      210.0   

   pixel 778  pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  
0      184.0      141.0       50.0        8.0       11.0       12.0  
1      157.0      144.0      130.0       98.0       73.0       15.0  
2      101.0       69.0      110.0       33.0       28.0       30.0  
3      119.0      135.0      143.0      159.0      120.0       85.0  
4      203.0      191.0      166.0       56.0        0.0        0.0  

[5 rows x 785 columns]

In [11]:
#konvert ke dalam format csv
df.to_csv('data_train_mnist.csv', sep=',', encoding='utf-8', index=False)

In [12]:
df.head()

label  pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  \
0    0.0     15.0     14.0     10.0     30.0     62.0     88.0    109.0   
1    1.0    121.0    140.0    151.0    170.0    171.0    194.0    196.0   
2    1.0     23.0    200.0     21.0     22.0     25.0     26.0     25.0   
3    1.0    101.0     82.0     90.0    100.0    137.0    145.0    178.0   
4    0.0     70.0     90.0    167.0    179.0     95.0     82.0     33.0   

   pixel 7  pixel 8    ...      pixel 774  pixel 775  pixel 776  pixel 777  \
0    129.0    114.0    ...          176.0      179.0      164.0      177.0   
1    188.0    172.0    ...          175.0      175.0      172.0      171.0   
2     22.0      6.0    ...          126.0      114.0      100.0       99.0   
3    125.0    141.0    ...          159.0      128.0      127.0      110.0   
4      0.0      0.0    ...          214.0      211.0      198.0      210.0   

   pixel 778  pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  
0      184.0      141.0       50.0        8.0       11.0       12.0  
1      157.0      144.0      130.0       98.0       73.0       15.0  
2      101.0       69.0      110.0       33.0       28.0       30.0  
3      119.0      135.0      143.0      159.0      120.0       85.0  
4      203.0      191.0      166.0       56.0        0.0        0.0  

[5 rows x 785 columns]

In [13]:
#membuka file csv yang sudah disimpan ke dalam dataframe
df1 = pd.read_csv('data_train_mnist.csv')
df1.head()

label  pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  \
0    0.0     15.0     14.0     10.0     30.0     62.0     88.0    109.0   
1    1.0    121.0    140.0    151.0    170.0    171.0    194.0    196.0   
2    1.0     23.0    200.0     21.0     22.0     25.0     26.0     25.0   
3    1.0    101.0     82.0     90.0    100.0    137.0    145.0    178.0   
4    0.0     70.0     90.0    167.0    179.0     95.0     82.0     33.0   

   pixel 7  pixel 8    ...      pixel 774  pixel 775  pixel 776  pixel 777  \
0    129.0    114.0    ...          176.0      179.0      164.0      177.0   
1    188.0    172.0    ...          175.0      175.0      172.0      171.0   
2     22.0      6.0    ...          126.0      114.0      100.0       99.0   
3    125.0    141.0    ...          159.0      128.0      127.0      110.0   
4      0.0      0.0    ...          214.0      211.0      198.0      210.0   

   pixel 778  pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  
0      184.0      141.0       50.0        8.0       11.0       12.0  
1      157.0      144.0      130.0       98.0       73.0       15.0  
2      101.0       69.0      110.0       33.0       28.0       30.0  
3      119.0      135.0      143.0      159.0      120.0       85.0  
4      203.0      191.0      166.0       56.0        0.0        0.0  

[5 rows x 785 columns]